### ISSUE TITLE
Deleted entry mentions the future

### ISSUE THREAD

**Issue by wbazant** [ebi-uniprot/uniprot-website#39]
This entry was deleted on 2019-05-08:
https://www.uniprot.org/uniprot/A0A068X338

The text says:
On August 5, 2019 this entry was deleted.

Looks like a bug wrong text formatting happens somewhere.

**Comment by xwatkins** [comment]
Thanks for the feedback! However, this repo is for the future UniProt website, could you please email help@uniprot.org  instead?
